services:
  flowise:
    image: flowiseai/flowise
    container_name: ${FLOWISE_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: flowise_db
    volumes:
      - ${VOL_FLOWISE_DATA:-${PROJECT_DATA_DIR:-../data}/flowise}:/root/.flowise

    networks:
      - ai-apps-network
      - data-network
    healthcheck:
      test: [CMD-SHELL, 'wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  flowise_data:
