services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: ${LITELLM_CONTAINER_NAME}
    restart: unless-stopped
    command: ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/litellm_db"
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
    volumes:
      - ${PROJECT_APPS_DIR:-../apps}/litellm:/app/

    networks:
      - ai-network
      - data-network
    healthcheck:
      test: [CMD-SHELL, 'wget --no-verbose --tries=1 --spider http://localhost:4000/ || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
