services:
  minio:
    image: minio/minio
    container_name: ${MINIO_CONTAINER_NAME}
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${VOL_MINIO_DATA:-${PROJECT_DATA_DIR:-../data}/minio}:/data

    networks:
      - data-network

    healthcheck:
      test: [CMD-SHELL, 'curl -f http://localhost:9000/minio/health/live || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  minio_data:
