services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${RABBITMQ_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ${VOL_RABBITMQ_DATA:-${PROJECT_DATA_DIR:-../data}/rabbitmq}:/var/lib/rabbitmq

    networks:
      - optional-network

    healthcheck:
      test: [CMD-SHELL, 'rabbitmq-diagnostics -q ping']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  rabbitmq_data:
