services:
  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${VOL_REDIS_DATA:-${PROJECT_DATA_DIR:-../data}/redis}:/data
    networks:
      - data-network

    healthcheck:
      test: [CMD-SHELL, 'redis-cli ping']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  redis_data:
